[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "node server.js"
  targetPort = 3000

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200